/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package controlnotas;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author USUARIO
 */
public class ControlNotasSwing extends javax.swing.JFrame {

    /**
     * Creates new form ControlNotasSwing
     */
    public ControlNotasSwing() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbTema = new javax.swing.JLabel();
        lbNombre = new javax.swing.JLabel();
        lbCarrera = new javax.swing.JLabel();
        lbCiclo = new javax.swing.JLabel();
        lbCum = new javax.swing.JLabel();
        lbMensaje1 = new javax.swing.JLabel();
        tfNombre = new javax.swing.JTextField();
        tfCum = new javax.swing.JTextField();
        cbCarrera = new javax.swing.JComboBox<>();
        cbCiclo = new javax.swing.JComboBox<>();
        lbMateria = new javax.swing.JLabel();
        lbUv = new javax.swing.JLabel();
        lbNota = new javax.swing.JLabel();
        cbMateria1 = new javax.swing.JComboBox<>();
        cbUv1 = new javax.swing.JComboBox<>();
        tfNota1 = new javax.swing.JTextField();
        lbEstado1 = new javax.swing.JLabel();
        cbMateria2 = new javax.swing.JComboBox<>();
        cbUv2 = new javax.swing.JComboBox<>();
        tfNota2 = new javax.swing.JTextField();
        lbEstado2 = new javax.swing.JLabel();
        lbEstado3 = new javax.swing.JLabel();
        tfNota3 = new javax.swing.JTextField();
        cbUv3 = new javax.swing.JComboBox<>();
        cbMateria3 = new javax.swing.JComboBox<>();
        lbEstado4 = new javax.swing.JLabel();
        tfNota4 = new javax.swing.JTextField();
        cbUv4 = new javax.swing.JComboBox<>();
        cbMateria4 = new javax.swing.JComboBox<>();
        lbEstado5 = new javax.swing.JLabel();
        tfNota5 = new javax.swing.JTextField();
        cbUv5 = new javax.swing.JComboBox<>();
        cbMateria5 = new javax.swing.JComboBox<>();
        btCalcular = new javax.swing.JButton();
        lbMensaje = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 102));

        lbTema.setFont(new java.awt.Font("Sitka Small", 1, 24)); // NOI18N
        lbTema.setText("CONTROL DE NOTAS");

        lbNombre.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbNombre.setText("NOMBRE");

        lbCarrera.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbCarrera.setText("CARRERA");

        lbCiclo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbCiclo.setText("CICLO");

        lbCum.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbCum.setText("CUM");

        lbMensaje1.setBackground(new java.awt.Color(0, 255, 51));
        lbMensaje1.setFont(new java.awt.Font("Script MT Bold", 0, 14)); // NOI18N
        lbMensaje1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbMensaje1.setOpaque(true);

        tfNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNombreActionPerformed(evt);
            }
        });

        cbCarrera.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Seleccion --", "Ingenieria Industrial", "Ingenieria en Sistemas", "Ingenieria Electrica", "Ingenieria en Agronegocios" }));

        cbCiclo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Seleccion --", "Ciclo 01", "Ciclo 02", " " }));

        lbMateria.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbMateria.setText("MATERIA");

        lbUv.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbUv.setText("UV");

        lbNota.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbNota.setText("NOTA");

        cbMateria1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Opciones --", "Investigación de Operaciones I", "Electronica", "Legislación Aplicada a la Empresa", "Desarro de Software I", "Base de Datos II" }));

        cbUv1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Opciones --", "3", "4" }));
        cbUv1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        tfNota1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNota1ActionPerformed(evt);
            }
        });

        lbEstado1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbEstado1.setForeground(new java.awt.Color(255, 255, 255));
        lbEstado1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbEstado1.setText("Estado");

        cbMateria2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Opciones --", "Investigación de Operaciones I", "Electronica", "Legislación Aplicada a la Empresa", "Desarro de Software I", "Base de Datos II" }));

        cbUv2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Opciones --", "3", "4" }));
        cbUv2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lbEstado2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbEstado2.setForeground(new java.awt.Color(255, 255, 255));
        lbEstado2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbEstado2.setText("Estado");

        lbEstado3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbEstado3.setForeground(new java.awt.Color(255, 255, 255));
        lbEstado3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbEstado3.setText("Estado");

        cbUv3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Opciones --", "3", "4" }));
        cbUv3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        cbMateria3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Opciones --", "Investigación de Operaciones I", "Electronica", "Legislación Aplicada a la Empresa", "Desarro de Software I", "Base de Datos II" }));

        lbEstado4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbEstado4.setForeground(new java.awt.Color(255, 255, 255));
        lbEstado4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbEstado4.setText("Estado");

        tfNota4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNota4ActionPerformed(evt);
            }
        });

        cbUv4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Opciones --", "3", "4" }));
        cbUv4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        cbMateria4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Opciones --", "Investigación de Operaciones I", "Electronica", "Legislación Aplicada a la Empresa", "Desarro de Software I", "Base de Datos II" }));

        lbEstado5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbEstado5.setForeground(new java.awt.Color(255, 255, 255));
        lbEstado5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbEstado5.setText("Estado");

        cbUv5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Opciones --", "3", "4" }));
        cbUv5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        cbMateria5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Opciones --", "Investigación de Operaciones I", "Electronica", "Legislación Aplicada a la Empresa", "Desarro de Software I", "Base de Datos II" }));

        btCalcular.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btCalcular.setText("CALCULAR");
        btCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCalcularActionPerformed(evt);
            }
        });

        lbMensaje.setFont(new java.awt.Font("Script MT Bold", 1, 14)); // NOI18N
        lbMensaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbMensajeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(btCalcular)
                        .addGap(46, 46, 46)
                        .addComponent(lbMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 622, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbNombre))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbTema)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lbCarrera)
                                        .addGap(125, 125, 125)
                                        .addComponent(lbCiclo))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(cbCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(cbCiclo, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(37, 37, 37)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbCum)
                                    .addComponent(tfCum, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(lbMensaje1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbMateria2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(cbMateria1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(cbMateria3, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cbMateria4, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(cbMateria5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addComponent(lbMateria)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cbUv1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbUv2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbUv3, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbUv4, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbUv5, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(58, 58, 58)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfNota1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfNota2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfNota3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfNota4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfNota5, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbEstado5, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbEstado4, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbEstado3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbEstado2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbEstado1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(108, 108, 108)
                                .addComponent(lbUv)
                                .addGap(132, 132, 132)
                                .addComponent(lbNota)))))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTema)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNombre)
                    .addComponent(lbCarrera)
                    .addComponent(lbCiclo)
                    .addComponent(lbCum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfCum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbCiclo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbMensaje1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbMateria)
                            .addComponent(lbUv)
                            .addComponent(lbNota))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbMateria1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbUv1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfNota1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbEstado1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbMateria2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbUv2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cbMateria3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbUv3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cbMateria4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbUv4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbUv5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbMateria5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tfNota2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbEstado2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(12, 12, 12)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tfNota3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbEstado3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tfNota4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbEstado4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(12, 12, 12)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tfNota5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbEstado5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btCalcular)
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lbMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfNota1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNota1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNota1ActionPerformed

    private void tfNota4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNota4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNota4ActionPerformed

    private void btCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCalcularActionPerformed
        // TODO add your handling code here:
        String carrera = "";
        String ciclo = "";
        String nota = "";
        int uv1,uv2,uv3,uv4,uv5;
        int reprobado=0,aprobado=0;
        float cum;
        float nota1,nota2,nota3,nota4,nota5;
        
        String carreraSeleccionada = (String) cbCarrera.getSelectedItem();
        String cicloSeleccionado = (String) cbCiclo.getSelectedItem();
        String materia1 = (String) cbMateria1.getSelectedItem();
        String materia2 = (String) cbMateria2.getSelectedItem();
        String materia3 = (String) cbMateria3.getSelectedItem();
        String materia4 = (String) cbMateria4.getSelectedItem();
        String materia5 = (String) cbMateria5.getSelectedItem();
        String num1 = tfNota1.getText();
        String num2 = tfNota2.getText();
        String num3 = tfNota3.getText();
        String num4 = tfNota4.getText();
        String num5 = tfNota5.getText();
        String nombre = tfNombre.getText();
        String UVmateria1 = (String) cbUv1.getSelectedItem();
        String UVmateria2 = (String) cbUv2.getSelectedItem();
        String UVmateria3 = (String) cbUv3.getSelectedItem();
        String UVmateria4 = (String) cbUv4.getSelectedItem();
        String UVmateria5 = (String) cbUv5.getSelectedItem();
       
        // Llenar los campos que se piden
        if("Elegir una opción".equals(carreraSeleccionada) || "Elegir una opción".equals(cicloSeleccionado) 
                ||"Elegir una opción".equals(materia1) || "Elegir una opción".equals(materia2) || "Elegir una opción".equals(materia3)
                || "Elegir una opción".equals(materia4) || "Elegir una opción".equals(materia5) || "Elegir una opción".equals(UVmateria1)
                || "Elegir una opción".equals(UVmateria2) || "Elegir una opción".equals(UVmateria3) || "Elegir una opción".equals(UVmateria4)
                || "Elegir una opción".equals(UVmateria5) ||num1.isEmpty() || num2.isEmpty() || num3.isEmpty() || num4.isEmpty() || num5.isEmpty() || nombre.isEmpty()) {
            carrera = "-1";
            ciclo = "-1";
            
            JOptionPane.showMessageDialog(this, "Llene todos los campos solicitados.", "Error", JOptionPane.ERROR_MESSAGE);
        }
       
        // Convertir string a int y a float con un parseo
        nota1 = Float.parseFloat(num1); 
        nota2 = Float.parseFloat(num2); 
        nota3 = Float.parseFloat(num3); 
        nota4 = Float.parseFloat(num4); 
        nota5 = Float.parseFloat(num5); 
        uv1 = Integer.parseInt(UVmateria1);
        uv2 = Integer.parseInt(UVmateria2);
        uv3 = Integer.parseInt(UVmateria3);
        uv4 = Integer.parseInt(UVmateria4);
        uv5 = Integer.parseInt(UVmateria5);
        
        
        //Validar que las notas sean mayores a 0 y menores a 10
        if(!(nota1 <= 10) || !(nota1 >= 0) || !(nota2 <= 10) || !(nota2 >= 0) || !(nota3 <= 10) || !(nota3 >= 0) || !(nota4 <= 10) || !(nota4 >= 0)
                || !(nota5 <= 10) || !(nota5 >= 0)){
           nota = "-1";
           JOptionPane.showMessageDialog(this, "Ingrese un dato válido en notas.", "Error", JOptionPane.ERROR_MESSAGE);
        }
       
        // Mostrar Resultado 
        if(!"-1".equals(carrera) && !"-1".equals(ciclo) && !"-1".equals(nota)){
            
            //Le quitamos lo transparente que tiene por defecto a JLabel.
            lbEstado1.setOpaque(true);
            lbEstado2.setOpaque(true);
            lbEstado3.setOpaque(true);
            lbEstado4.setOpaque(true);
            lbEstado5.setOpaque(true);
            
             // Cambiar estado a Reprobado o Aprobado
        if(nota1 < 6){
            lbEstado1.setText("Reprobado");
            lbEstado1.setBackground(Color.orange);
            reprobado++;
        }else{
            lbEstado1.setText("Aprobado");
            lbEstado1.setBackground(Color.blue);
            aprobado++;
        }
        if(nota2 < 6){
            lbEstado2.setText("Reprobado");
            lbEstado2.setBackground(Color.orange);
            reprobado++;
        }else{
            lbEstado2.setText("Aprobado");
            lbEstado2.setBackground(Color.blue);
            aprobado++;
        }
        if(nota3 < 6){
            lbEstado3.setText("Reprobado");
            lbEstado3.setBackground(Color.orange);
            reprobado++;
        }else{
            lbEstado3.setText("Aprobado");
            lbEstado3.setBackground(Color.blue);
            aprobado++;
        }
        if(nota4 < 6){
            lbEstado4.setText("Reprobado");
            lbEstado4.setBackground(Color.orange);
            reprobado++;
        }else{
            lbEstado4.setText("Aprobado");
            lbEstado4.setBackground(Color.blue);
            aprobado++;
        }
        if(nota5 < 6){
            lbEstado5.setText("Reprobado");
            lbEstado5.setBackground(Color.orange);
            reprobado++;
        }else{
            lbEstado5.setText("Aprobado");
            lbEstado5.setBackground(Color.blue);
            aprobado++;
        }
        
        //Cálculo del CUM
        cum = ((nota1*uv1)+(nota2*uv2)+(nota3*uv3)+(nota4*uv4)+(nota5*uv5))/(uv1+uv2+uv3+uv4+uv5);
        
        // Convertir double e int a string
        String TotalCum = Float.toString(cum);
        String MateriasAprobadas = Integer.toString(aprobado);
        String MateriasReprobadas = Integer.toString(reprobado);
        
            tfCum.setText(TotalCum);
            
            lbMensaje.setText(this.tfNombre.getText()
                + " su estado actual es de "
                + MateriasAprobadas 
                 + "\n"   
                + " materias aprobadas y "
                + MateriasReprobadas
                 +"\n" 
                + " reprobadas y su CUM actual es de "
                + this.tfCum.getText());
        }
    }//GEN-LAST:event_btCalcularActionPerformed

    
  // Validaciones para que solo se puedan ingresar numeros o letras en el campo correspondiente
 
    private void tfNota1KeyTyped(java.awt.event.KeyEvent evt) {                                 
        // TODO add your handling code here:
        // Cada vez que el usuario presione una tecla se genera un evento y se almacena en evt
        char c = evt.getKeyChar();
        if(c<'0' || c>'9')evt.consume();
    }                                

    private void tfNota2KeyTyped(java.awt.event.KeyEvent evt) {                                 
        // TODO add your handling code here:
         char c = evt.getKeyChar();
        if(c<'0' || c>'9')evt.consume();
    }                                

    private void tfNota3KeyTyped(java.awt.event.KeyEvent evt) {                                 
        // TODO add your handling code here:
         char c = evt.getKeyChar();
        if(c<'0' || c>'9')evt.consume();
    }                                

    private void tfNota4KeyTyped(java.awt.event.KeyEvent evt) {                                 
        // TODO add your handling code here:
         char c = evt.getKeyChar();
        if(c<'0' || c>'9')evt.consume();
    }                                

    private void tfNota5KeyTyped(java.awt.event.KeyEvent evt) {                                 
        // TODO add your handling code here:
         char c = evt.getKeyChar();
        if(c<'0' || c>'9')evt.consume();
    }                                

    private void tfNombreKeyTyped(java.awt.event.KeyEvent evt) {                                  
       
        // KeyTyped = evento de tecla
         char c = evt.getKeyChar(); // obteniendo el carácter ingresado desde el evento de tecla (evt). getKeyChar()
                                    // Devuelve el caracter de la tecla que se presionó
        if((c<'a' || c>'z') && (c<'A' || c>'Z') //Verifica si el carácter está fuera del rango de letras minúsculas y mayúsculas.
                && !(Character.isSpaceChar(c))) //Verifica si el carácter no es un espacio.
            evt.consume(); // Si el carácter ingresado no es una letra ni un espacio, este comando consume el evento de tecla
                           // así que no se mostrará en el campo de texto
    }          
    
    
    private void tfNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNombreActionPerformed

    private void lbMensajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbMensajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbMensajeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ControlNotasSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ControlNotasSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ControlNotasSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ControlNotasSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ControlNotasSwing().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCalcular;
    private javax.swing.JComboBox<String> cbCarrera;
    private javax.swing.JComboBox<String> cbCiclo;
    private javax.swing.JComboBox<String> cbMateria1;
    private javax.swing.JComboBox<String> cbMateria2;
    private javax.swing.JComboBox<String> cbMateria3;
    private javax.swing.JComboBox<String> cbMateria4;
    private javax.swing.JComboBox<String> cbMateria5;
    private javax.swing.JComboBox<String> cbUv1;
    private javax.swing.JComboBox<String> cbUv2;
    private javax.swing.JComboBox<String> cbUv3;
    private javax.swing.JComboBox<String> cbUv4;
    private javax.swing.JComboBox<String> cbUv5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbCarrera;
    private javax.swing.JLabel lbCiclo;
    private javax.swing.JLabel lbCum;
    private javax.swing.JLabel lbEstado1;
    private javax.swing.JLabel lbEstado2;
    private javax.swing.JLabel lbEstado3;
    private javax.swing.JLabel lbEstado4;
    private javax.swing.JLabel lbEstado5;
    private javax.swing.JLabel lbMateria;
    private javax.swing.JTextField lbMensaje;
    private javax.swing.JLabel lbMensaje1;
    private javax.swing.JLabel lbNombre;
    private javax.swing.JLabel lbNota;
    private javax.swing.JLabel lbTema;
    private javax.swing.JLabel lbUv;
    private javax.swing.JTextField tfCum;
    private javax.swing.JTextField tfNombre;
    private javax.swing.JTextField tfNota1;
    private javax.swing.JTextField tfNota2;
    private javax.swing.JTextField tfNota3;
    private javax.swing.JTextField tfNota4;
    private javax.swing.JTextField tfNota5;
    // End of variables declaration//GEN-END:variables
}
